### ISSUE TITLE
thread 'main' panicked at src/dump_image.rs:390:53:

### ISSUE THREAD

**Issue by skischus** [rudihorn/drm-vc4-grabber#15]
hello and thanks for the project. on my rpi3 with osmc everything runs perfectly. 
now i wanted to run the whole thing on a rpi4 with osmc (latest version) and always get the same error message, no matter if i use the release or compile it myself.

`osmc@osmc-rpi4:~$ ./drm-vc4-grabber-v0.1.1-aarch64-linux/drm-vc4-grabber
Setting color
linear, size: (1920, 1080), pitch: 7680, bpp: 32, length: 2073600
thread 'main' panicked at src/dump_image.rs:390:53:
called `Result::unwrap()` on an `Err` value: InvalidArgument
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

`osmc@osmc-rpi4:~$ ./drm-vc4-grabber/target/arm-unknown-linux-gnueabihf/release/drm-vc4-grabber
Setting color
linear, size: (1920, 1080), pitch: 7680, bpp: 32, length: 2073600
thread 'main' panicked at src/dump_image.rs:390:53:
called `Result::unwrap()` on an `Err` value: InvalidArgument
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

`osmc@osmc-rpi4:~$ RUST_BACKTRACE=1 ./drm-vc4-grabber/target/arm-unknown-linux-gnueabihf/release/drm-vc4-grabber
Setting color
thread 'main' panicked at src/dump_image.rs:390:53:
called `Result::unwrap()` on an `Err` value: InvalidArgument
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   3: drm_vc4_grabber::dump_image::dump_framebuffer_to_image
   4: drm_vc4_grabber::dump_and_send_framebuffer
   5: drm_vc4_grabber::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
osmc@osmc-rpi4:~$ RUST_BACKTRACE=full ./drm-vc4-grabber/target/arm-unknown-linux-gnueabihf/release/drm-vc4-grabber
Setting color
thread 'main' panicked at src/dump_image.rs:390:53:
called `Result::unwrap()` on an `Err` value: InvalidArgument
stack backtrace:
   0:   0x6beb6c - std::backtrace_rs::backtrace::libunwind::trace::h12b352c498b75433
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:   0x6beb6c - std::backtrace_rs::backtrace::trace_unsynchronized::h3af32b06e035abe7
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:   0x6beb6c - std::sys_common::backtrace::_print_fmt::he2a3e2a40522362c
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:   0x6beb6c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7c7da4e3f58c35a9
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:   0x6e82a8 - core::fmt::rt::Argument::fmt::h171b714554d3e2c0
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:   0x6e82a8 - core::fmt::write::h8eaf408dc91384a1
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:   0x6bc2ec - std::io::Write::write_fmt::h5a545a5758e420d3
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:   0x6be980 - std::sys_common::backtrace::_print::hedb58f3b22cd053a
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:   0x6be980 - std::sys_common::backtrace::print::h8401c095f39b094d
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:   0x6c0220 - std::panicking::default_hook::{{closure}}::ha0184dce5f3892e0
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:272:22
  10:   0x6bfdf0 - std::panicking::default_hook::hbef41816fef2feb8
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:   0x6c07e4 - std::panicking::rust_panic_with_hook::h065d96e0b10e7cb0
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
  12:   0x6c0620 - std::panicking::begin_panic_handler::{{closure}}::h2ae0851a511bd5e4
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
  13:   0x6bf0d4 - std::sys_common::backtrace::__rust_end_short_backtrace::h63f698f9d59cce8f
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  14:   0x6c03d8 - rust_begin_unwind
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  15:   0x61cc34 - core::panicking::panic_fmt::hce533fbcf593601a
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  16:   0x61d0b4 - core::result::unwrap_failed::hf39f3ea91c255745
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
  17:   0x6237b0 - drm_vc4_grabber::dump_image::dump_framebuffer_to_image::h69a9be222cd78c40
  18:   0x624c34 - drm_vc4_grabber::dump_and_send_framebuffer::h493eb2aeade8b813
  19:   0x625e80 - drm_vc4_grabber::main::hc2c7e970d93f7d8a
  20:   0x62995c - std::sys_common::backtrace::__rust_begin_short_backtrace::hba050d1d1b0fcef6
  21:   0x628ddc - std::rt::lang_start::{{closure}}::h853b23be4841dd93
  22:   0x6b84d0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he6de3c9ba182c7ea
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
  23:   0x6b84d0 - std::panicking::try::do_call::h85a18615958f5abc
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  24:   0x6b84d0 - std::panicking::try::h70efe73187b84719
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  25:   0x6b84d0 - std::panic::catch_unwind::h474c9062ce6e9374
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  26:   0x6b84d0 - std::rt::lang_start_internal::{{closure}}::hb429fb51f13df81c
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  27:   0x6b84d0 - std::panicking::try::do_call::h46b09fb7dc292cbd
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  28:   0x6b84d0 - std::panicking::try::hc3b4dd5e528f413e
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  29:   0x6b84d0 - std::panic::catch_unwind::h6e59759c7dc195f2
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  30:   0x6b84d0 - std::rt::lang_start_internal::he015df6632cca5cb
                       at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  31:   0x628dc4 - std::rt::lang_start::hbb3e82d7aea9039f
  32: 0xf781fa20 - __libc_start_main
`

**Comment by skischus** [comment]
was able to solve the problem myself. 
with sudo ./drm-vc4-grabber it worked
