### ISSUE TITLE
thread 'main' panicked at src/main.rs:185:53:

### ISSUE THREAD

**Issue by thawn** [rudihorn/drm-vc4-grabber#21]
Using Libreelec 12.0.1 on a raspi 4b

I get the following error when I start the binary:

```
thread 'main' panicked at src/main.rs:185:53:
called `Result::unwrap()` on an `Err` value: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }
```

**Comment by MPowed** [comment]
Is hyperion running and setup?

**Comment by rudihorn** [comment]
Has this been resolved?
